src/AppBundle/Entity/Course/Attendee.php
<?php

namespace AppBundle\Entity\Course;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Intl\Intl;

/**
 * Attendee
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AppBundle\Entity\Repository\AttendeeRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Attendee
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="title", type="integer", nullable=true)
     */
    private $title;

    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Length(max=250)
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     * family name
     * @Assert\NotBlank()
     * @Assert\Length(max=250)
     * @ORM\Column(name="surname", type="string", length=255)
     */
    private $surname;

    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Length(max=250)
     * @Assert\Email(checkMX = true)
     * @ORM\Column(name="email", type="string", length=255)
     */
    private $email;

    /**
     * @var string
     * @Assert\Length(max=250)
     * @ORM\Column(name="tel", type="string", length=255, nullable=true)
     */
    private $tel;

    /**
     * @var boolean
     * pays less
     * @ORM\Column(name="reduced_eligible", type="boolean")
     */
    private $reducedEligible;

    /**
     * @ORM\ManyToMany(targetEntity="Course", mappedBy="attendees")
     */
    private $courses;

    /**
     * @ORM\Column(name="transactionId", type="string", length=255, nullable=true)
     */
    private $transactionId;

    /**
     * @ORM\Column(name="paymentStatus", type="string", length=255, nullable=true)
     */
    private $paymentStatus;

    /**
     * @ORM\Column(name="uniqID", type="string", length=255, nullable=true)
     */
    private $uniqID;

    /**
     * @ORM\Column(name="updatedAt", type="datetime")
     */
    private $updatedAt;

    /**
     * @var string
     * @Assert\Length(max=500)
     * @ORM\Column(name="info", type="string", length=500, nullable=true)
     */
    private $info;

    /**
     * @var boolean
     * if the attendee was present at the course or not.
     * @ORM\Column(name="present", type="boolean", options={"default" = false}, nullable=true)
     */
    private $present;

    /**
     * @ORM\Column(name="adress", type="string", length=200, nullable=true)
     * @Assert\Length(max=200)
     * @Assert\NotBlank()
     */
    private $adress;

    /**
     * @ORM\Column(name="zipcode", type="string", length=20, nullable=true)
     * @Assert\Length(max=20)
     * @Assert\NotBlank()
     */
    private $zipcode;

    /**
     * @ORM\Column(name="city", type="string", length=120, nullable=true)
     * @Assert\Length(max=120)
     * @Assert\NotBlank()
     */
    private $city;

    /**
     * @ORM\Column(name="country", type="string", length=20, nullable=true)
     * @Assert\Length(max=20)
     * @Assert\NotBlank()
     */
    private $country;

    /**
     * @ORM\Column(name="dsgvo", type="boolean", options={"default" = false}, nullable=true)
     * @Assert\IsTrue()
     */
    private $dsgvo;

    /**
     * @ORM\Column(name="newsletter", type="boolean", options={"default" = false}, nullable=true)
     */
    private $newsletter;

    public function getDsgvo()
    {
        return $this->dsgvo;
    }

    public function setDsgvo($dsgvo)
    {
        $this->dsgvo = $dsgvo;
        return $this;
    }

    public function getNewsletter()
    {
        return $this->newsletter;
    }

    public function setNewsletter($newsletter)
    {
        $this->newsletter = $newsletter;
        return $this;
    }

    public function __toString()
    {
        return $this->name.' '.$this->surname;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Attendee
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set surname
     *
     * @param string $surname
     * @return Attendee
     */
    public function setSurname($surname)
    {
        $this->surname = $surname;

        return $this;
    }

    /**
     * Get surname
     *
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Attendee
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set tel
     *
     * @param string $tel
     * @return Attendee
     */
    public function setTel($tel)
    {
        $this->tel = $tel;

        return $this;
    }

    /**
     * Get tel
     *
     * @return string
     */
    public function getTel()
    {
        return $this->tel;
    }

    /**
     * Set reducedEligible
     *
     * @param boolean $reducedEligible
     * @return Attendee
     */
    public function setReducedEligible($reducedEligible)
    {
        $this->reducedEligible = $reducedEligible;

        return $this;
    }

    /**
     * Get reducedEligible
     *
     * @return boolean
     */
    public function getReducedEligible()
    {
        return $this->reducedEligible;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->uniqID = uniqID();
        $this->courses = new \Doctrine\Common\Collections\ArrayCollection();
        $this->updatedAt = new \DateTime();
        $this->present = false;
    }

    /**
     * Add courses
     *
     * @param \AppBundle\Entity\Course $courses
     * @return Attendee
     */
    public function addCourse($course)
    {
        $this->courses[] = $course;
        return $this;
    }

    /**
     * Remove courses
     *
     * @param \AppBundle\Entity\Course $course
     */
    public function removeCourse($course)
    {
        $this->courses->removeElement($course);
        return $this;
    }

    /**
     * Get courses
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCourses()
    {
        return $this->courses;
    }

    /**
     * Set transactionId
     *
     * @param string $transactionId
     * @return Attendee
     */
    public function setTransactionId($transactionId)
    {
        $this->transactionId = $transactionId;

        return $this;
    }

    /**
     * Get transactionId
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transactionId;
    }

    /**
     * Set paymentStatus
     *
     * @param string $paymentStatus
     * @return Attendee
     */
    public function setPaymentStatus($paymentStatus)
    {
        $this->paymentStatus = $paymentStatus;

        return $this;
    }

    /**
     * Get paymentStatus
     *
     * @return string
     */
    public function getPaymentStatus()
    {
        return $this->paymentStatus;
    }

    /**
     * Set uniqID
     *
     * @param string $uniqID
     * @return Attendee
     */
    public function setUniqID($uniqID)
    {
        $this->uniqID = $uniqID;

        return $this;
    }

    /**
     * Get uniqID
     *
     * @return string
     */
    public function getUniqID()
    {
        return $this->uniqID;
    }

    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function setUpdatedAt()
    {
        $this->updatedAt = new \DateTime();
        return $this;
    }

    public function getInfo()
    {
        return $this->info;
    }

    public function setInfo($info)
    {
        $this->info = $info;
        return $this;
    }

    public function getPresent()
    {
        return $this->present;
    }

    public function isPresent()
    {
        return $this->present;
    }

    public function wasPresent()
    {
        return $this->present;
    }

    public function setPresent($present)
    {
        $this->present = $present;
        return $this;
    }

    public function getAdress()
    {
        return $this->adress;
    }

    public function setAdress($adress)
    {
        $this->adress = $adress;
        return $this;
    }

    public function setZipcode($zipcode)
    {
        $this->zipcode = $zipcode;
        return $this;
    }

    public function getZipcode()
    {
        return $this->zipcode;
    }

    public function setCountry($country)
    {
        $this->country = $country;
        return $this;
    }

    public function getCountry()
    {
        return $this->country;
    }

    public function getCity()
    {
        return $this->city;
    }

    public function setCity($city)
    {
        $this->city = $city;
        return $this;
    }

     public function getCountryname()
    {
        return Intl::getRegionBundle()->getCountryName($this->getCountry());
    }
}

src/AppBundle/Controller/Backend/CommentController.php
<?php

namespace AppBundle\Controller\Backend;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use AppBundle\Entity\Comment;
use AppBundle\Form\Backend\RemoveCommentType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

/**
 * Series backend controller.
 *
 * @Route("/backend/comment")
 * @Security("is_granted('ROLE_USER')")
 */
class CommentController extends Controller
{
    /**
     * @Route("s", name="oktolab_backend_comment_index")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $page = $request->query->get('page', 1);
        $results = $request->query->get('results', 10);
        $em = $this->getDoctrine()->getManager();
        $paginator = $this->get('knp_paginator');
        $comments = $paginator->paginate(
            $em->getRepository('AppBundle:Comment')->findComments(0, true),
            $page,
            $results
        );

        return ['comments' => $comments];
    }

    /**
     * @Route("/{comment}/show", name="oktothek_backend_comment_show")
     * @Template()
     */
    public function showAction(Comment $comment)
    {
        return ['comment' => $comment];
    }

    /**
     * @Route("/{comment}/remove", name="oktothek_backend_comment_remove")
     * @Template()
     */
    public function removeAction(Request $request, Comment $comment)
    {
        $form = $this->createForm(RemoveCommentType::class, $comment);
        $form->add('submit', SubmitType::class, ['label' => 'oktothek.slide_update_button', 'attr' => ['class' => 'btn btn-primary']]);
        $form->add('delete', SubmitType::class, ['label' => 'oktothek.slide_delete_button', 'attr' => ['class' => 'btn btn-danger']]);

        if ($request->getMethod() == "POST") { //sends form
            $form->handleRequest($request);
            if ($form->isValid()) {
                if ($form->get('submit')->isClicked()) {
                    $em = $this->getDoctrine()->getManager();
                    $em->persist($comment);
                    $em->flush();
                    $this->get('session')->getFlashBag()->add('success', 'oktothek.success_update_comment');

                    return $this->redirect($this->generateUrl('oktothek_backend_comment_show', ['comment' => $comment->getId()]));
                } else { //delete
                    $this->get('oktothek_slide')->deleteSlide($comment);
                    $this->get('session')->getFlashBag()->add('success', 'oktothek.success_delete_comment');
                    return $this->redirect($this->generateUrl('oktolab_backend_comment_index'));
                }
            } else {
                $this->get('session')->getFlashBag()->add('error', 'oktothek.error_update_comment');
            }
        }

        return ['form' => $form->createView()];
    }
}

src/AppBundle/Controller/Backend/CoursepackageController.php
<?php

namespace AppBundle\Controller\Backend;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use AppBundle\Entity\Course\Coursepackage;
use AppBundle\Entity\Course\CoursepackageSelect;
use AppBundle\Form\Course\CoursepackageType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

/**
 * @Route("/backend/coursepackage")
 */
class CoursepackageController extends Controller
{
    /**
     * @Route("/", name="oktothek_backend_coursepackages")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $coursepackages = $em->getRepository('AppBundle:Course\Coursepackage')->findAll();

        return ['coursepackages' => $coursepackages];
    }

    /**
     * @Route("/new", name="oktothek_backend_new_coursepackage")
     * @Template()
     */
    public function newAction(Request $request)
    {
        $coursepackage = new Coursepackage();
        $em = $this->getDoctrine()->getManager();
        $coursetypes = $em->getRepository('AppBundle:Course\Coursetype')->findAll();

        $form = $this->createForm(CoursepackageType::class, $coursepackage, ['coursetypes' => $coursetypes]);
        $form->add('submit', SubmitType::class, ['label' => 'oktothek.coursepackage_create_button', 'attr' => ['class' => 'btn btn-primary']]);

        if ($request->getMethod() == "POST") { //sends form
            $form->handleRequest($request);
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($coursepackage);
                $em->flush();
                $this->get('session')->getFlashBag()->add('success', 'oktothek.success_create_coursepackage');

                return $this->redirect($this->generateUrl('oktothek_backend_coursepackages'));
            } else {
                $this->get('session')->getFlashBag()->add('error', 'oktothek.error_create_coursepackage');
            }
        }

        return ['form' => $form->createView()];
    }

    /**
     * @Route("/edit/{coursepackage}", name="oktothek_backend_edit_coursepackage")
     * @Template()
     */
    public function editAction(Request $request, Coursepackage $coursepackage)
    {
        $em = $this->getDoctrine()->getManager();
        $coursetypes = $em->getRepository('AppBundle:Course\Coursetype')->findAll();

        $form = $this->createForm(CoursepackageType::class, $coursepackage, ['coursetypes' => $coursetypes]);
        $form->add('delete', SubmitType::class, ['label' => 'oktothek.coursepackage_delete_button', 'attr' => ['class' => 'btn btn-danger']]);
        $form->add('submit', SubmitType::class, ['label' => 'oktothek.coursepackage_edit_button', 'attr' => ['class' => 'btn btn-primary']]);

        if ($request->getMethod() == "POST") { //sends form
            $form->handleRequest($request);
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                if ($form->get('submit')->isClicked()) {
                    $em->persist($coursepackage);
                    $em->flush();
                    $this->get('session')->getFlashBag()->add('success', 'oktothek.success_edit_coursepackage');

                    return $this->redirect($this->generateUrl('oktothek_backend_coursepackages'));
                } else { //delete
                    $em->remove($coursepackage);
                    $em->flush();
                    $this->get('session')->getFlashBag()->add('success', 'oktothek.success_delete_coursepackage');
                    return $this->redirect($this->generateUrl('oktothek_backend_coursepackages'));
                }
            } else {
                $this->get('session')->getFlashBag()->add('error', 'oktothek.error_edit_coursepackage');
            }
        }

        return ['form' => $form->createView(), 'coursepackage' => $coursepackage];
    }

    /**
     * @Route("/show/{coursepackage}", name="oktothek_backend_show_coursepackage")
     * @Template()
     */
    public function showAction(Coursepackage $coursepackage)
    {
        return ['coursepackage' => $coursepackage];
    }
}

src/AppBundle/Resources/views/backend/attendee/create.html.twig
{% extends "BprsStyleBundle::layout.html.twig" %}
{% block title %}{{ name|default('OKTO')~' | '~'oktothek_academy_header'|trans }}{% endblock %}
{% block nav_head%}
    {% include 'BprsStyleBundle::menu.html.twig' with {'selected': 'academy', 'dropdown': ''} %}
{% endblock %}

{% set body_class = "academy" %}
{% block body %}
<div class="container">
    <header class="page-header">
        <h1>{{ 'oktothe_academy_book_course_header'|trans({'%coursetype%': course.coursetype.title}) }}</h1>
	</header>
    <section>
    <p>{{ course.coursetype.description }}</p>
    </section>
    <section>
    <h2>{{ 'oktothek_academy_bC_dates'|trans }}</h2>
    {% for date in course.dates %}
    <span>{{ 'oktothek_academy_timetable_date'|trans({'%day%': 'oktothek_academy_timetable_days_choice'|transchoice(date.courseStart|date('N')), '%date%': date.courseStart|date('oktothek_academy_timetable_date_format'|trans)})}}</span>
    {{ 'oktothek_academy_timetable_time'|trans({'start': date.courseStart|date('oktothek_academy_timetable_time_format'|trans), 'end': date.courseEnd|date('oktothek_academy_timetable_time_format'|trans)}) }}
    {% endfor %}
    {% if course.coursetype.price <= 0 %}
        <p>{{ 'oktothek_academy_course_free'|trans }}</p>
    {% else %}
        <p>{{ 'oktothek_academy_misc_info'|trans({'%price%': course.coursetype.price|number_format(2, ',', '.'), '%price_reduced%': course.coursetype.priceReduced|number_format(2, ',', '.')})|raw }}</p>
    {% endif %}
    {{ form_start(form) }}
    {{ form_end(form) }}
    <p><small>{{ 'oktothek_academy_show_footnote'|trans }}</small></p>
    </section>
</div>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/app/css/academy.css') }}" rel="stylesheet" />
{% endblock %}

src/AppBundle/Resources/views/backend/attendee/edit.html.twig
{% extends "BprsStyleBundle::layout.html.twig" %}
{% block title %}{{ name|default('OKTO')~' | '~'oktothek_academy_header'|trans }}{% endblock %}
{% block nav_head%}
    {% include 'BprsStyleBundle::menu.html.twig' with {'selected': 'academy', 'dropdown': ''} %}
{% endblock %}

{% set body_class = "academy" %}
{% block body %}
<div class="container">
    <header class="page-header">
        <h1></h1>
	</header>

    {{ form_start(form) }}
    {{ form_end(form) }}

</div>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/app/css/academy.css') }}" rel="stylesheet" />
{% endblock %}

src/AppBundle/Resources/views/backend/attendee/index.html.twig
{% extends "BprsStyleBundle::layout.html.twig" %}

{% block nav_head%}
    {% include 'BprsStyleBundle::menu.html.twig' with {'selected': 'oktothek_backend', 'dropdown': ''} %}
{% endblock %}
{% block body_main %}
    <ul class="nav nav-tabs">
      <li role="presentation">
          <a href="{{ path('oktothek_backend_courses') }}">
              {{ 'oktothek.backend_academy_course_header'|trans}}
          </a>
      </li>
      <li role="presentation">
          <a href="{{ path('oktothek_backend_coursepackages') }}">
              {{ 'oktothek.backend_academy_package_header'|trans}}
          </a>
      </li>
      <li role="presentation" class="active">
          <a href="{{ path('oktothek_backend_attendee_index') }}">
              {{ 'oktothek.backend_academy_attendee_header'|trans }}
          </a>
      </li>
    </ul>
    <div class="page-header">
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="filter_menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                {{ 'oktothek.backend_attendee_dropdown'|trans|raw }}
            </button>
            <ul class="dropdown-menu" aria-labelledby="filter_menu">
                <li {% if attendees.isSorted('a.email') %}class="active"{% endif %}>
                    {{ knp_pagination_sortable(attendees, 'oktothek.academy_backend_attendee_email'|trans, 'a.email') }}
                </li>
                <li {% if attendees.isSorted('a.name') %}class="active"{% endif %}>
                    {{ knp_pagination_sortable(attendees, 'oktothek.academy_backend_attendee_name'|trans, 'a.name') }}
                </li>
                <li {% if attendees.isSorted('a.surname') %}class="active"{% endif %}>
                    {{ knp_pagination_sortable(attendees, 'oktothek.academy_backend_attendee_surname'|trans, 'a.surname') }}
                </li>
                <li {% if attendees.isSorted('a.updatedAt') %}class="active"{% endif %}>
                    {{ knp_pagination_sortable(attendees, 'oktothek.academy_backend_attendee_date'|trans, 'a.updatedAt') }}
                </li>
            </ul>
        </div>
    </div>
    <div class="navigation">
        {{ knp_pagination_render(attendees) }}
    </div>
    {% for attendee in attendees %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="{{ path('oktothek_backend_show_attendee', {'attendee': attendee.id}) }}">
                    {{
                        'oktothek.backend_attendee_full_name'|trans({
                            '%title%': 'oktothek_attendee_title_choice'|transchoice(attendee.title),
                            '%firstname%': attendee.name,
                            '%lastname%': attendee.surname
                        })
                    }}
                </a>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>{{ 'oktothek.backend_attendee_info_email'|trans }}</dt>
                    <dd>{{ attendee.email }}</dd>
                    <dt>{{ 'oktothek.backend_attendee_info_tel'|trans }}</dt>
                    <dd>{{ attendee.tel|default('oktothek.backend_attendee_info_no_tel'|trans) }}</dd>
                    <dt>{{ 'oktothek.backend_attendee_info_date'|trans }}</dt>
                    <dd>{{ attendee.updatedAt|date('oktothek.backend_attendee_info_date_format'|trans) }}</dd>
                </dl>
            </div>
            <div class="list-group">
                {% for course in attendee.courses if attendee.courses is not empty %}
                    <a href="{{ path('oktothek_backend_show_course', {'course': course.id})  }}" class="list-group-item">
                        {{ course.coursetype }}
                    </a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    <div class="navigation">
        {{ knp_pagination_render(attendees) }}
    </div>
{% endblock %}

src/AppBundle/Resources/views/backend/attendee/move_attendee.html.twig
{% extends "BprsStyleBundle::layout.html.twig" %}

{% block nav_head%}
    {% include 'BprsStyleBundle::menu.html.twig' with {'selected': 'oktothek_backend', 'dropdown': ''} %}
{% endblock %}
{% block body_main %}
    <div class="page-header">
        <h1>{{ attendee }}</h1>
        <a href="{{ path('oktothek_backend_attendee_index') }}" class="btn btn-default">{{ 'oktothek.backend_attendee_show_back_to_index'|trans|raw }}</a>
    </div>
    {{ form(form) }}
{% endblock %}

src/AppBundle/Resources/views/backend/attendee/show.html.twig
{% extends "BprsStyleBundle::layout.html.twig" %}

{% block nav_head%}
    {% include 'BprsStyleBundle::menu.html.twig' with {'selected': 'oktothek_backend', 'dropdown': ''} %}
{% endblock %}
{% block body_main %}
    <div class="page-header">
        <h1>Kursteilnehmer</h1>
        <!-- Single button -->
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ 'oktothek_backend_show_course_dropdown'|trans|raw }}
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a href="{{ path('oktothek_backend_attendee_index') }}">
                        {{ 'oktothek.backend_attendee_show_back_to_index'|trans|raw }}
                    </a>
                </li>
                <li>
                    <a href="{{ path('oktothek_backend_move_attendee', {'attendee': attendee.id})}}">
                        {{ 'oktothek.backend_attendee_move_to_course'|trans|raw }}
                    </a>
                </li>
                <li>
                    <a href="{{ path('oktothek_backend_edit_attendee', {'attendee': attendee.id})}}">
                        {{ 'oktothek.backend_attendee_edit'|trans|raw }}
                    </a>
                </li>
                <li>
                    <a href="{{ path('oktothek_backend_edit_paymentstatus', {'attendee': attendee.id}) }}">
                        {{ 'oktothek.backend_attendee_update_paymentstatus'|trans|raw }}
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>{{ 'attendee_info_title'|trans }}</dt>
                <dd>{{ 'oktothek_attendee_title_choice'|transchoice(attendee.title) }}</dd>

                <dt>{{ 'attendee_info_name'|trans }}</dt>
                <dd>{{ attendee.name }}</dd>

                <dt>{{ 'attendee_info_surname'|trans }}</dt>
                <dd>{{ attendee.surname }}</dd>

                <dt>{{ 'oktothek.backend_attendee_info_email'|trans }}</dt>
                <dd>{{ attendee.email }}</dd>

                <dt>{{ 'oktothek.backend_attendee_info_tel'|trans }}</dt>
                <dd>{{ attendee.tel|default('oktothek.backend_attendee_info_no_tel'|trans) }}</dd>

                <dt>{{ 'oktothek.backend_attendee_info_date'|trans }}</dt>
                <dd>{{ attendee.updatedAt|date('oktothek.backend_attendee_info_date_format'|trans) }}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>{{ 'attendee_info_adress'|trans }}</dt>
                <dd>{{ attendee.adress }}</dd>

                <dt>{{ 'attendee_info_zipcode'|trans }}</dt>
                <dd>{{ attendee.zipcode }}</dd>

                <dt>{{ 'attendee_info_city'|trans }}</dt>
                <dd>{{ attendee.city }}</dd>

                <dt>
                    {{ 'attendee_info_country'|trans }}
                </dt>
                <dd>
                    {{ attendee.countryname }}
                </dd>
            </dl>
        </div>
        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>{{ 'attendee_info_reduced'|trans }}</dt>
                <dd>{{ 'attendee_info_reduced_choice'|transchoice(attendee.reducedEligible) }}</dd>

                <dt>{{ 'attendee_info_transactionId'|trans }}</dt>
                <dd>{{ attendee.transactionId }}</dd>

                <dt>{{ 'attendee_info_paymentStatus'|trans }}</dt>
                <dd>{{ attendee.paymentStatus|trans }}</dd>
            </dl>
            <dl class="dl-horizontal">
                {% if attendee.courses is not empty %}
                    {% for course in attendee.courses %}
                        <dt>{{ 'attendee_info_course'|trans }}</dt>
                        <dd>
                            <a href="{{ path('oktothek_backend_show_course', {'course': course.id})}}">
                                {{ course.coursetype }}
                            </a>
                        </dd>
                    {% endfor %}
                {% endif %}
            </dl>
        </div>
    </div>
{% endblock %}