vendor_repo/oktolab/media-bundle/Oktolab/MediaBundle/Entity/Playlist.php
<?php

namespace Oktolab\MediaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use Symfony\Component\Validator\Constraints as Assert;

interface PlaylistInterface {
    public function getItems();
    public function addItem($item);
    public function removeItem($item);
}

/**
 * Playlist
 *
 * @ORM\Table()
 * @ORM\MappedSuperclass()
 * @JMS\ExclusionPolicy("all")
 * @ORM\HasLifecycleCallbacks()
 * JMS\AccessType("public_method")
 */
class Playlist
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @JMS\ReadOnly
     */
    private $id;

    /**
     * @Assert\NotNull()
     * @var string
     * @JMS\Expose
     * @JMS\Type("string")
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
    * @var string
    * @JMS\Expose
    * @JMS\Type("string")
    * @ORM\Column(name="uniqID", type="string", length=13)
    */
    private $uniqID;

    /**
     * @Assert\Length(max = 450)
     * @var string
     * @JMS\Expose
     * @JMS\Type("string")
     * @ORM\Column(name="description", type="string", length=500, nullable=true)
     */
    private $description;

    /**
     * @var \DateTime
     * @JMS\Expose
     * @JMS\Type("DateTime")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     * @JMS\Expose
     * @JMS\Type("DateTime")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Playlist
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Playlist
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set createdAt
     * @ORM\PrePersist
     * @param \DateTime $createdAt
     * @return Episode
     */
    public function setCreatedAt()
    {
        $this->createdAt = new \DateTime();
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @param \DateTime $updatedAt
     * @return Episode
     */
    public function setUpdatedAt()
    {
        $this->updatedAt = new \DateTime();
        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->uniqID = uniqid();
    }

    /**
     * Set uniqID
     *
     * @param string $uniqID
     * @return Playlist
     */
    public function setUniqID($uniqID)
    {
        $this->uniqID = $uniqID;

        return $this;
    }

    /**
     * Get uniqID
     *
     * @return string
     */
    public function getUniqID()
    {
        return $this->uniqID;
    }
}

vendor_repo/oktolab/media-bundle/Oktolab/MediaBundle/Form/MediaType.php
<?php

namespace Oktolab\MediaBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Bprs\AssetBundle\Form\Type\AssetType;
use Oktolab\MediaBundle\Entity\Media;

class MediaType extends AbstractType
{
    private $trans;

    public function __construct($trans)
    {
        $this->trans = $trans;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'quality',
                TextType::class,
                [
                    'label' => 'oktolab_media_quality_label',
                    'attr' => [
                        'placeholder' => 'oktolab_media_media_quality_placeholder'
                    ]
                ]
            )
            ->add('status', ChoiceType::class, [
                'choices' => [
                    $this->trans->transchoice('oktolab_media.media_status_choice', Media::OKTOLAB_MEDIA_STATUS_MEDIA_TOPROGRESS) => Media::OKTOLAB_MEDIA_STATUS_MEDIA_TOPROGRESS,
                    $this->trans->transchoice('oktolab_media.media_status_choice', Media::OKTOLAB_MEDIA_STATUS_MEDIA_INPROGRESS) => Media::OKTOLAB_MEDIA_STATUS_MEDIA_INPROGRESS,
                    $this->trans->transchoice('oktolab_media.media_status_choice', Media::OKTOLAB_MEDIA_STATUS_MEDIA_FINISHED) => Media::OKTOLAB_MEDIA_STATUS_MEDIA_FINISHED
                ]
            ])
            ->add('public', CheckboxType::class, ['required' => false, 'label' => 'oktolab_media_public_label'])
            ->add('sortNumber', IntegerType::class, ['label' => 'oktolab_media_sortNumber_label'])
            ->add('progress', IntegerType::class, ['label' => 'oktolab_media_progress_label'])
            ->add('asset', AssetType::class, ['label' => 'oktolab_media_asset_label']);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'Oktolab\MediaBundle\Entity\Media'
        ]);
    }

    public function getName()
    {
        return 'oktolab_media_mediatype';
    }
}

vendor_repo/oktolab/media-bundle/Oktolab/MediaBundle/Resources/views/player/jwplayer.js.twig
<script src="{{ player_url|raw }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var playerInstance = jwplayer("{{ player_id }}");
        playerInstance.setup({
            logo:   {{ origin(episode)|raw }},
            {% if displaytitle %}
                displaytitle: true,
            {% else %}
                displaytitle: false,
            {% endif %}
            playlist: [{
                image: "{{ episode.posterframe|thumb(720,1280) }}",
                title: "{{ episode.name }}",
                {% if episode.stereomode == 1 %}
                    stereomode: 'monoscopic',
                {% elseif episode.stereomode == 2 %}
                    stereomode: 'stereoscopicTopBottom',
                {% elseif episode.stereomode == 3 %}
                    stereomode: 'stereoscopicLeftRight',
                {% endif %}
                sources: [
                    {% for media in episode.media %}
                        {
                            file: "{{ media.asset|link }}",
                            label: "{{ media.quality }}",
                            type: "mp4"
                        }{% if not loop.last %},{% endif %}
                    {% endfor %}
                ],
                tracks: [
                    {% if episode.sprite is not empty %}
                        {
                            file: "{{ url('oktolab_media_sprite_for_episode', {'uniqID': episode.uniqID}) }}",
                            kind: "{{ constant('Oktolab\\MediaBundle\\Entity\\Caption::OKTOLAB_CAPTIONKIND_THUMB') }}"
                        },
                    {% endif %}
                    {% for caption in episode.captions %}
                        {
                            file: "{{ url('oktolab_media_caption_for_episode', {'uniqID': caption.uniqID}) }}",
                            label: "{{ caption.label }}",
                            kind: "{{ caption.kind }}"
                        }{% if not loop.last %},{% endif %}
                    {% endfor %}
                ]
            }]
        });
    });
</script>

vendor_repo/oktolab/media-bundle/Oktolab/MediaBundle/Resources/views/player/jwplayer_live.js.twig
<script src="{{ player_url|raw }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var playerInstance = jwplayer("{{ player_id }}");
        playerInstance.setup({
            {% if displaytitle %}
                displaytitle: true,
            {% else %}
                displaytitle: false,
            {% endif %}
            playlist: [{
                {# image: "{{ stream.posterframe|thumb(720,1280) }}", #}
                title: "{{ stream.name }}",
                {% if stream.stereomode == 1 %}
                    stereomode: 'monoscopic',
                {% elseif stream.stereomode == 2 %}
                    stereomode: 'stereoscopicTopBottom',
                {% elseif stream.stereomode == 3 %}
                    stereomode: 'stereoscopicLeftRight',
                {% endif %}
                file: "{{ stream|publicAdressForStream }}"
            }]
        });
    });
</script>

vendor_repo/oktolab/media-bundle/Oktolab/MediaBundle/Resources/views/player/playlist_jwplayer.js.twig
<script src="{{ player_url|raw }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var playerInstance = jwplayer("{{ player_id }}");
        playerInstance.setup({
            {% if displaytitle %}
                displaytitle: true,
            {% else %}
                displaytitle: false,
            {% endif %}
            playlist: [
                {% for playlistItem in playlist.items %}
                {
                    image: "{{ playlistItem.episode.posterframe(true)|thumb(720,1280)}}",
                    title: "{{ playlistItem.episode.name }}",
                    {% if playlistItem.episode.stereomode == 1 %}
                        stereomode: 'monoscopic',
                    {% elseif playlistItem.episode.stereomode == 2 %}
                        stereomode: 'stereoscopicTopBottom',
                    {% elseif playlistItem.episode.stereomode == 3 %}
                        stereomode: 'stereoscopicLeftRight',
                    {% endif %}
                    sources: [
                        {% for media in playlistItem.episode.media %}
                                {
                                    file: "{{ media.asset|link }}",
                                    label: "{{ media.quality }}",
                                    type: "mp4"
                                }{% if not loop.last %},{% endif %}
                        {% endfor %}
                    ],
                    tracks: [
                        {% for caption in playlistItem.episode.captions %}
                            {
                                file: "{{ url('oktolab_media_caption_for_episode', {'uniqID': caption.uniqID}) }}",
                                label: "{{ caption.label }}",
                                kind: "{{ caption.kind }}"
                            }{% if not loop.last %},{% endif %}
                        {% endfor %}
                    ]
                }{% if not loop.last %},{% endif %}
                {% endfor %}
            ]
        });
    });
</script>